name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pytest pytest-cov flake8 black pylint pre-commit
        pip install -e .
    - name: Run pre-commit
      run: pre-commit run --all-files
    - name: Commit formatted code
      if: github.event_name == 'push'
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        black .
        git config user.name "GitHub Actions"
        git config user.email "actions@github.com"
        git commit -am "chore: format with black" || echo "No changes to commit"
        git push
    - name: Lint
      run: |
        flake8
        black --check .
    - name: Pylint
      continue-on-error: true
      run: |
        pylint egg egg_cli.py | tee pylint.log
    - name: Run tests with coverage
      run: |
        pytest --cov=egg --cov=egg_cli --cov-report=xml \
               --cov-report=term-missing:skip-covered -q
    - name: Update badges
      if: github.event_name == 'push'
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        python scripts/update_badges.py
        git config user.name "GitHub Actions"
        git config user.email "actions@github.com"
        git commit -am "chore: update badges" || echo "No badge updates"
        git push
